spring:
  datasource:
    name: mytest
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mytest?useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8

mybatis:
  type-aliases-package: sloth.zhang.test.domain
  mapper-locations: classpath:/mapper/*.xml
